service: s3-lab

plugins:
  - serverless-pseudo-parameters
custom:
  bucket: random-bucket-s3-pan

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
            

functions:
  getObject:
    handler: handler.handler
    